### ISSUE TITLE
Lasts forever

### ISSUE THREAD

**Issue by bwsw** [bwsw/t-streams#142]
http://pastebin.com/ahhaQ22W

**Comment by bwsw** [comment]
[Thread-7] ERROR com.bwsw.tstreams.agents.producer.Transaction - Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] in 100 SECONDS.
[Thread-7] WARN com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - [FIRSTFAILLOCKABLE EXECUTOR] task failure; stop executor
[Thread-7] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
[main] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - Lock java.util.concurrent.locks.ReentrantLock@394d1531[Unlocked] / Exception is: com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$FirstFailLockableExecutorException: Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
[main] ERROR com.bwsw.tstreams.agents.producer.Transaction - Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Unlocked] / Exception is: com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$FirstFailLockableExecutorException: Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
[Thread-6] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - Lock java.util.concurrent.locks.ReentrantLock@394d1531[Unlocked] / Exception is: com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$FirstFailLockableExecutorException: Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
Exception in thread "Thread-6" com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$FirstFailLockableExecutorException: Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply$mcV$sp(FirstFailLockableTaskExecutor.scala:88)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.common.LockUtil$.withLockOrDieDo(LockUtil.scala:49)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor.submit(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.agents.producer.Producer$$anon$1$$anonfun$run$1.apply$mcV$sp(Producer.scala:125)
	at scala.util.control.Breaks.breakable(Breaks.scala:38)
	at com.bwsw.tstreams.agents.producer.Producer$$anon$1.run(Producer.scala:118)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$FirstFailLockableExecutorException: Token 1100202477 / Lock java.util.concurrent.locks.ReentrantLock@5b080f3a[Locked by thread main] / Failed to get lock object in 100 SECONDS.
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply$mcV$sp(FirstFailLockableTaskExecutor.scala:88)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$$anonfun$submit$1.apply(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.common.LockUtil$.withLockOrDieDo(LockUtil.scala:49)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor.submit(FirstFailLockableTaskExecutor.scala:80)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply$mcV$sp(Transaction.scala:258)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply(Transaction.scala:254)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply(Transaction.scala:254)
	at com.bwsw.tstreams.common.LockUtil$.withLockOrDieDo(LockUtil.scala:49)
	at com.bwsw.tstreams.agents.producer.Transaction.checkpoint(Transaction.scala:254)
	at com.bwsw.t_sreams.hello.Hello$$anonfun$main$1.apply$mcVI$sp(Main.scala:66)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.bwsw.t_sreams.hello.Hello$.main(Main.scala:62)
	at com.bwsw.t_sreams.hello.Hello.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
