### ISSUE TITLE
TS-156 uncaught exception

### ISSUE THREAD

**Issue by alexander-branevskiy** [bwsw/t-streams#168]
[main] ERROR com.bwsw.tstreams.agents.producer.Transaction$ - Lock java.util.concurrent.locks.ReentrantLock@65b3a85a[Unlocked] / Exception is: java.lang.IllegalStateException: Update takes too long (> 10 seconds). Probably failure.
Exception in thread "main" java.lang.IllegalStateException: Update takes too long (> 10 seconds). Probably failure.
	at com.bwsw.tstreams.agents.producer.TransactionState.awaitUpdateComplete(TransactionState.scala:103)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply$mcV$sp(Transaction.scala:270)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply(Transaction.scala:269)
	at com.bwsw.tstreams.agents.producer.Transaction$$anonfun$checkpoint$1.apply(Transaction.scala:269)
	at com.bwsw.tstreams.common.LockUtil$.withLockOrDieDo(LockUtil.scala:49)
	at com.bwsw.tstreams.agents.producer.Transaction.checkpoint(Transaction.scala:269)
	at com.bwsw.tstreams.HelloProducer$$anonfun$main$1.apply$mcVI$sp(Hello.scala:45)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at com.bwsw.tstreams.HelloProducer$.main(Hello.scala:41)

**Comment by alexander-branevskiy** [comment]
http://ideone.com/CZkCHL
