### ISSUE TITLE
ProducerMasterChangeTest

### ISSUE THREAD

**Issue by bwsw** [bwsw/t-streams#409]
```
[ExecutorGraph-materialize-id-0-0] ERROR org.apache.zookeeper.server.NIOServerCnxnFactory - Thread Thread[ExecutorGraph-materialize-id-0-0,5,main] died
java.lang.IllegalStateException: Executor com.bwsw.tstreams.common.FirstFailLockableTaskExecutor@24243111[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 590] is failed. No new tasks are allowed.
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitTo(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitToPublish(ExecutorGraph.scala:53)
	at com.bwsw.tstreams.coordination.producer.PeerAgent.submitPipelinedTaskToPublishExecutors(PeerAgent.scala:414)
	at com.bwsw.tstreams.agents.producer.Producer.openTransactionLocal(Producer.scala:265)
	at com.bwsw.tstreams.coordination.messages.master.NewTransactionRequest$$anonfun$handleP2PRequest$1.apply$mcV$sp(Messages.scala:86)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at com.bwsw.tstreams.agents.producer.Producer.materialize(Producer.scala:348)
	at com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.handleP2PRequest(Messages.scala:301)
	at com.bwsw.tstreams.coordination.messages.master.IMessage$class.run(Messages.scala:51)
	at com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.run(Messages.scala:297)
	at com.bwsw.tstreams.coordination.producer.PeerAgent$$anonfun$2.apply$mcV$sp(PeerAgent.scala:390)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by bwsw** [comment]
```
[ExecutorGraph-materialize-id-0-0] WARN com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - Task <ExecutorGraphTask> :: <MaterializeTask> has delayed Full in executor ExecutorGraph-materialize-id-0 for 3034 msecs. Threshold is: 120 msecs.
[ExecutorGraph-materialize-id-0-0] WARN com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - Task <ExecutorGraphTask> :: <MaterializeTask> has run in executor ExecutorGraph-materialize-id-0 for 3034 msecs. Threshold is: 20 msecs.
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - scala.Predef$.assert(Predef.scala:156)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.agents.producer.Producer.materialize(Producer.scala:348)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.handleP2PRequest(Messages.scala:301)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.messages.master.IMessage$class.run(Messages.scala:51)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.run(Messages.scala:297)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.PeerAgent$$anonfun$2.apply$mcV$sp(PeerAgent.scala:390)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ExecutorGraph-materialize-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.lang.Thread.run(Thread.java:745)
[ExecutorGraph-materialize-id-0-0] ERROR org.apache.zookeeper.server.NIOServerCnxnFactory - Thread Thread[ExecutorGraph-materialize-id-0-0,5,main] died
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:156)
	at com.bwsw.tstreams.agents.producer.Producer.materialize(Producer.scala:348)
	at com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.handleP2PRequest(Messages.scala:301)
	at com.bwsw.tstreams.coordination.messages.master.IMessage$class.run(Messages.scala:51)
	at com.bwsw.tstreams.coordination.messages.master.MaterializeRequest.run(Messages.scala:297)
	at com.bwsw.tstreams.coordination.producer.PeerAgent$$anonfun$2.apply$mcV$sp(PeerAgent.scala:390)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalStateException: Executor com.bwsw.tstreams.common.FirstFailLockableTaskExecutor@3f110ead[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 622] is failed. No new tasks are allowed.
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitTo(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitToPublish(ExecutorGraph.scala:53)
	at com.bwsw.tstreams.coordination.producer.PeerAgent.submitPipelinedTaskToPublishExecutors(PeerAgent.scala:414)
	at com.bwsw.tstreams.agents.producer.Producer.openTransactionLocal(Producer.scala:265)
	at com.bwsw.tstreams.coordination.messages.master.NewTransactionRequest$$anonfun$handleP2PRequest$1.apply$mcV$sp(Messages.scala:86)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - scala.collection.immutable.List.foreach(List.scala:381)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitTo(ExecutorGraph.scala:38)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitToPublish(ExecutorGraph.scala:53)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.PeerAgent.submitPipelinedTaskToPublishExecutors(PeerAgent.scala:414)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.agents.producer.Producer.openTransactionLocal(Producer.scala:265)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.messages.master.NewTransactionRequest$$anonfun$handleP2PRequest$1.apply$mcV$sp(Messages.scala:86)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ExecutorGraph-cassandra-id-0-0] ERROR com.bwsw.tstreams.common.FirstFailLockableTaskExecutor - java.lang.Thread.run(Thread.java:745)
[ExecutorGraph-cassandra-id-0-0] ERROR org.apache.zookeeper.server.NIOServerCnxnFactory - Thread Thread[ExecutorGraph-cassandra-id-0-0,5,main] died
java.lang.IllegalStateException: Executor com.bwsw.tstreams.common.FirstFailLockableTaskExecutor@3f110ead[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 622] is failed. No new tasks are allowed.
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$1.apply(ExecutorGraph.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitTo(ExecutorGraph.scala:38)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph.submitToPublish(ExecutorGraph.scala:53)
	at com.bwsw.tstreams.coordination.producer.PeerAgent.submitPipelinedTaskToPublishExecutors(PeerAgent.scala:414)
	at com.bwsw.tstreams.agents.producer.Producer.openTransactionLocal(Producer.scala:265)
	at com.bwsw.tstreams.coordination.messages.master.NewTransactionRequest$$anonfun$handleP2PRequest$1.apply$mcV$sp(Messages.scala:86)
	at com.bwsw.tstreams.coordination.producer.ExecutorGraph$$anonfun$submitTo$2$$anon$1.run(ExecutorGraph.scala:41)
	at com.bwsw.tstreams.common.FirstFailLockableTaskExecutor$RunnableWithoutLock.run(FirstFailLockableTaskExecutor.scala:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
сен 16, 2016 2:58:23 PM com.twitter.common.zookeeper.DistributedLockImpl unlock
INFO: Cleaning up this locks ephemeral node.
сен 16, 2016 2:58:23 PM com.twitter.common.zookeeper.DistributedLockImpl cleanup

```
