### ISSUE TITLE
TTS doesn't create some ZooKeeper nodes

### ISSUE THREAD

**Issue by tomskikh** [bwsw/t-streams#705]
```
Exception in thread "main" org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /tts
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:103)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:1426)
	at org.apache.curator.utils.ZKPaths.mkdirs(ZKPaths.java:291)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:746)
	at org.apache.curator.framework.imps.CreateBuilderImpl$11.call(CreateBuilderImpl.java:723)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.CreateBuilderImpl.pathInForeground(CreateBuilderImpl.java:720)
	at org.apache.curator.framework.imps.CreateBuilderImpl.protectedPathInForeground(CreateBuilderImpl.java:484)
	at org.apache.curator.framework.imps.CreateBuilderImpl.forPath(CreateBuilderImpl.java:474)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:349)
	at org.apache.curator.framework.imps.CreateBuilderImpl$4.forPath(CreateBuilderImpl.java:291)
	at org.apache.curator.framework.recipes.atomic.DistributedAtomicValue.initialize(DistributedAtomicValue.java:199)
	at org.apache.curator.framework.recipes.atomic.DistributedAtomicLong.initialize(DistributedAtomicLong.java:96)
	at com.bwsw.tstreamstransactionserver.netty.server.zk.ZKIDGenerator.<init>(ZKIDGenerator.scala:22)
	at com.bwsw.tstreamstransactionserver.netty.server.zk.ZookeeperClient.idGenerator(ZookeeperClient.scala:44)
	at com.bwsw.tstreamstransactionserver.netty.server.singleNode.SingleNodeServer.<init>(SingleNodeServer.scala:147)
	at com.bwsw.tstreamstransactionserver.netty.server.singleNode.SingleNodeServerBuilder.build(SingleNodeServerBuilder.scala:109)
	at com.bwsw.tstreamstransactionserver.SingleNodeServerLauncher$.delayedEndpoint$com$bwsw$tstreamstransactionserver$SingleNodeServerLauncher$1(SingleNodeServerLauncher.scala:67)
	at com.bwsw.tstreamstransactionserver.SingleNodeServerLauncher$delayedInit$body.apply(SingleNodeServerLauncher.scala:28)
```

**Comment by Krisilda** [comment]
@placccebo could you please check that task because it looks like we merged it without review.
