### ISSUE TITLE
Implement a test to check deletion of ledgers under the regular work of the server (with transactions creation)

### ISSUE THREAD

**Issue by placccebo** [bwsw/t-streams#745]
add to CommonCheckpointGroupServerTtlTest:
1. 
- create a server bundle (set a small number of  ENTRY_LOG_SIZE_LIMIT of bookkeeper server)
- open the required number of txns to roll over the initial entryLog (0.log) 
- wait the time that is more than dataCompactionInterval but is less than expungeDelaySec
- check that ledgers exist in bk and zk and there are more that one (0.log) entry logs
- wait the time that is more than expungeDelaySec
- check that expired ledgers don't exist in bk and zk
- check that there is only the initial entry log

2. 
- create a server bundle
- open a txn
- wait the time that is more than dataCompactionInterval but is less than expungeDelaySec
- check that ledgers exist in bk and zk
- wait the time that is more than expungeDelaySec
- check that expired ledgers don't exist in bk and zk
- checkpoint first txn, open a new one and checkpoint it
- check that client receives both txns

**Comment by placccebo** [comment]
the first test should have the following steps:

- create a server bundle (set a small number of ENTRY_LOG_SIZE_LIMIT and SKIP_LIST_SIZE_LIMIT of bookkeeper server, both are measured in bytes)
- open the required number of txns to roll over the initial entryLog (0.log), also implement a method to get a request size to estimate the required number of txns
- wait the time that is more than dataCompactionInterval but is less than expungeDelaySec
- check that ledgers exist in bk and zk and there are more that one (0.log) entry logs
- wait the time that is more than expungeDelaySec
- check that expired ledgers don't exist in bk and zk
- check that there is only the initial entry log

**Comment by placccebo** [comment]
CI has been fixed and tests fail sometimes

**Comment by placccebo** [comment]
tests fail because of an attempt to read znode data that doesn't exist:
`org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /tree/common/d90427e1-048c-4cb4-9db6-92334eab76e2/0/0/0/8
[info]   at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
[info]   at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
[info]   at org.apache.zookeeper.ZooKeeper.getData(ZooKeeper.java:1215)
[info]   at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:310)
[info]   at org.apache.curator.framework.imps.GetDataBuilderImpl$4.call(GetDataBuilderImpl.java:299)
[info]   at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
[info]   at org.apache.curator.framework.imps.GetDataBuilderImpl.pathInForeground(GetDataBuilderImpl.java:296)
[info]   at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:287)
[info]   at org.apache.curator.framework.imps.GetDataBuilderImpl.forPath(GetDataBuilderImpl.java:34)
[info]   at com.bwsw.tstreamstransactionserver.netty.server.multiNode.bookkeeperService.hierarchy.ZookeeperTreeList.getNextNode(ZookeeperTreeList.scala:103)
[info]   at com.bwsw.tstreamstransactionserver.util.multiNode.CommonCheckpointGroupServerTtlUtils$.addNodes(CommonCheckpointGroupServerTtlUtils.scala:66)
[info]   at com.bwsw.tstreamstransactionserver.util.multiNode.CommonCheckpointGroupServerTtlUtils$.$anonfun$ledgersExistInZkTree$1(CommonCheckpointGroupServerTtlUtils.scala:56)
[info]   at com.bwsw.tstreamstransactionserver.util.multiNode.CommonCheckpointGroupServerTtlUtils$.$anonfun$ledgersExistInZkTree$1$adapted(CommonCheckpointGroupServerTtlUtils.scala:55)
[info]   at scala.collection.immutable.Set$Set2.foreach(Set.scala:130)
[info]   at com.bwsw.tstreamstransactionserver.util.multiNode.CommonCheckpointGroupServerTtlUtils$.ledgersExistInZkTree(CommonCheckpointGroupServerTtlUtils.scala:55)
[info]   at com.bwsw.tstreamstransactionserver.netty.server.multiNode.IdleCommonCheckpointGroupServerTtlTest.$anonfun$new$2(IdleCommonCheckpointGroupServerTtlTest.scala:122)
[info]   at com.bwsw.tstreamstransactionserver.netty.server.multiNode.IdleCommonCheckpointGroupServerTtlTest.$anonfun$new$2$adapted(IdleCommonCheckpointGroupServerTtlTest.scala:110)
`

**Comment by placccebo** [comment]
It happens when creation of a new ledger (hence a znode too) has been during deletion process of other ledger and root data became inconsistent (id of first and last ledgers)
